project 'BreakPoint.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'BreakPoint' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BreakPoint
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
end
